name: "Add Jira link to PR"

on:
 workflow_call:
    inputs:
      jira-instance-url:
        description: "URL to Jira instance"
        required: false
        default: "https://rtbhouseproduct.atlassian.net/browse"
        type: "string"
      jira-project-id:
        description: "Jira project name"
        required: false
        default: "APPS"
        type: "string"
    secrets:
      github-token:
        required: true
        description: "GitHub token"

jobs:
  add_comment_about_jira_item:
    runs-on: ubuntu-latest
    env:
     jira-prefix: "${{ inputs.jira-project-id }}-"
     pr-title: ${{ github.event.pull_request.title }}
    steps:
      - name: Replace special characters in PR title and store title in txt file
        run: |
          echo "${{ env.pr-title }}" | sed 's/(/ /g' | sed 's/)/ /g' | sed 's/#/ /g' | sed "s/'/ /g" | sed 's/\"/ /g' | sed 's/\\/ /g' | sed 's/\// /g' >> temp.txt
          echo "pr_title_escaped=$(cat temp.txt)" >> $GITHUB_ENV
          rm temp.txt
      - name: Get Jira ID from PR title
        run: echo "jira-id=$(echo $pr_title_escaped | awk 'BEGIN { FS = " " } ; { print $1 }')" >> $GITHUB_ENV
      - name: Add comment with link to Jira
        if: startsWith(env.pr-title, env.jira-prefix)
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.github-token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Jira link [${{ env.jira-id }}](${{ inputs.jira-instance-url }}/${{ env.jira-id }})"
            })
      - name: Add comment about missing Jira ID
        if: ${{ !startsWith(env.pr-title, env.jira-prefix) }}
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.github-token }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "PR title should start with Jira ID like `${{ env.jira-prefix }}1234 feat: add super feature`"
            })
